[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_gifs = "HuLCc7aj2iw2Zfb2XbVsNQpiixa6MhydxkSdf5CsMTvY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/vlad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
